######################### 数据源配置 dataSourceConfig start #########################
# 数据库驱动名称
db.driverName=com.mysql.jdbc.Driver
# 驱动连接的url
db.url=jdbc:mysql://106.54.209.225:3307/cuhk_mkt?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF8
#db.url=jdbc:mysql://10.10.78.48:3306/customer_center?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF8
# 数据库连接用户名
db.username=root
#db.username=crm_query
# 数据库连接密码
db.password=e31TOPwL
#db.password=skscrm123456
######################### 数据源配置 dataSourceConfig end #########################


#########################  数据库表策略配置 strategyConfig start #########################
# 表示生成实体时忽略的表前缀名，如：表名为"wms_item_brand"，配置为"wms_"，生成后的实体为"ItemBrand"。多个以","隔开
sc.tablePrefix=biz_
# 需要生成的表实体，多个以","隔开，允许正则表达式
sc.include=biz_course_category
# 需要排除的表名，允许正则表达式（与include二选一配置）
sc.exclude=
# 自定义继承的Entity类全称，带包名
sc.superEntityClass=com.uneed.common.mybatis.model.SuperModel
# 自定义基础的Entity类，公共字段
sc.superEntityColumns=id,created_by,created_date,updated_by,updated_date,remove_flag
# 自定义继承的Mapper类全称，带包名
sc.superMapperClass=com.uneed.common.mybatis.base.SuperMapper
# 自定义继承的Service类全称，带包名
sc.superServiceClass=com.uneed.common.mybatis.base.SuperService
# 自定义继承的ServiceImpl类全称，带包名
sc.superServiceImplClass=com.uneed.common.mybatis.base.SuperServiceImpl
# 自定义继承的Controller类全称，带包名
sc.superControllerClass=com.uneed.common.support.base.AbstractRestController
# 表名称映射实体类名称规则是否驼峰（默认 true）
sc.namingCamel=true
# 是否生成实体时，生成字段注解（默认 true）
sc.entityTableFieldAnnotationEnable=true
# 【实体】是否为lombok模型（默认 true）
sc.entityLombokModel=true
# 【实体】是否为构建者模型（默认 false）
sc.entityBuilderModel=false
# 生成@RestController控制器 （默认 true）
sc.restControllerStyle=true
# controller请求path驼峰转连字符 （默认 true）
sc.controllerMappingHyphenStyle=true
# 实体是否生成 serialVersionUID （默认 true）
sc.entitySerialVersionUID=true
#########################  数据库表策略配置 strategyConfig end #########################


#########################  全局配置 globalConfig start #########################
# 生成文件的输出目录
gc.output=/Users/taokai/program/generator/code
# 是否覆盖已有文件（默认 true）
gc.fileOverride=true
# 代码生成完毕后是否打开输出目录（默认 true）
gc.open=true
# 是否在xml中添加二级缓存配置（默认 false）
gc.enableCache=false
# 开发人员
gc.author=taok
# 是否开启swagger2模式（默认 true）
gc.swagger2=true
# 是否开启ActiveRecord模式（默认 false）
gc.activeRecord=false
# 是否开启BaseResultMap（默认 false）
gc.baseResultMap=false
# 是否开启BaseColumnList（默认 false）
gc.baseColumnList=false
# 开启 Kotlin 模式（默认 false）
gc.kotlin=false
# 时间类型对应策略：ONLY_DATE，使用java.util.date包下的类型；SQL_PACK，使用java.sql包下的类型；TIME_PACK，使用java.time包下的类型，表示java8新时间类型
gc.dateType=ONLY_DATE
##注意事项：以下%s为占位符，会自动填充。如：为user表生成代码，则%s会替换为"User"
# 实体命名方式
gc.entityName=
# mapper命名方式
gc.mapperName=%sMapper
# mapper xml命名方式
gc.xmlName=%sMapper
# service命名方式
gc.serviceName=%sService
# service impl命名方式
gc.serviceImplName=%sServiceImpl
# controller命名方式
gc.controllerName=%sController
#########################  全局配置 globalConfig end #########################


#########################  包名配置 packageConfig start #########################
# 父包名。如果为空，将下面子包名必须写全部， 否则就只需写子包名
pc.parent=cn.edu.cuhk.mkt
# 父包模块名，拼接在
pc.moduleName=biz
# Entity包名
pc.entity=entity
# Service包名
pc.service=service
# Service Impl包名
pc.serviceImpl=service.impl
# Mapper包名
pc.mapper=mapper
# Controller包名
pc.controller=controller
#########################  包名配置 packageConfig end #########################


#########################  模版配置 templateConfig start #########################
## 以下均为模版文件路径
# Java 实体类模板
tp.entity=template/entity.java.vm
# Service 类模板
tp.service=template/service.java.vm
# Service Impl 实现类模板
tp.serviceImpl=template/serviceImpl.java.vm
# Mapper 模板
tp.mapper=template/mapper.java.vm
# controller 控制器模板
tp.controller=template/controller.java.vm
#########################  模版配置 templateConfig end #########################


######################### 自定义参数配置 start #########################
# 注入自定义配置，可以在 VM 中使用 cfg. 设置的值
# AbstractModelConverter 路径及类名
cfg.superConverterClass=AbstractModelConverter
cfg.superConverterClassPackage=com.uneed.common.support.convert.AbstractModelConverter
# 这里自定了Controller类上的请求路径前缀，路径为前缀+模块名称+请求路径，如：@RequestMapping("/api/item/unit")
cfg.requestPrefix=
cfg.variableRequestPrefix=${adminPath}
# 标记controller是否生成设置数据有效性的方法（默认 false）
cfg.controllerActive=false
# 标记controller是否生成通用导入方法（默认 false）
cfg.controllerImport=false
# 标记controller是否生成通用导出方法（默认 false）
cfg.controllerExport=false
# 这里自定了Client类上的请求路径前缀，路径为前缀+模块名称+请求路径，如：path = "/client/item/unit"
cfg.clientPrefix=client
# 标记是否生成client方法（默认 true）
cfg.generateClient=false
######################### 自定义参数配置 start #########################
