# 本地环境配置
spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
    dynamic:
      primary: primary
      druid:
        filters: stat
      datasource:
        primary:
          url: jdbc:postgresql://10.20.217.87:15432/sme_ugo_graduate
          username: sme_ugo_graduate
          password: c21lX3Vnb19ncmFkdWF0ZQ==
          driver-class-name: org.postgresql.Driver
          defaultAutoCommit: false

  redis:
    # Redis数据库索引（默认为0）
    database: ${REDIS_DB:0}
    # Redis服务器地址
    host: ${REDIS_HOST:106.54.209.225}
    # Redis服务器连接端口
    port: ${REDIS_PORT:6379}
    # Redis服务器连接密码（默认为空）
    password: ${REDIS_PASSWORD:378251}
    # 连接超时时间（毫秒）
    timeout: ${REDIS_TIMEOUT:3000}
    # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
    testOnBorrow: true
    # 在空闲时检查有效性, 默认false
    testWhileIdle: true
    # 是否进行有效性检查
    testOnReturn: true
    jedis:
      # redis连接池
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 10
        # 连接池中的最小空闲连接 默认 0
        min-idle: 2

# 公共配置
common:
  redisPrefix: MKT-LOCAL

# Minio 配置
minio:
  # Minio服务器地址
  endpoint: http://106.54.209.225:9000
  # 访问的key
  accessKey: admin
  # 访问的秘钥
  secretKey: "cuhk@VrdUy%mJ6c#Ts"
  # false: http，true: https
  secure: false
  # 默认存储桶
  bucketName: cuhk
  # 文件大小（MB）
  maxSize: 20
  # 存储目录
  dir: /mkt-local
  # 访问网关：下载文件服务器地址
  gateway: http://localhost:10050${adminPath}/common/oss/download
